import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("setup", "routes/setup.tsx"),
  route("sign-in", "routes/sign-in.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("sign-out", "routes/sign-out.tsx"),
  route("invite/:token", "routes/invite.tsx"),
  route("recover/:token", "routes/recover.tsx"),
  route("people", "routes/people.tsx"),
  route("integrations", "routes/integrations.tsx"),
  route("account", "routes/account.tsx"),
  route("imports", "routes/import-index.tsx"),
  route("imports/:sessionId", "routes/import-review.tsx"),
  route("cookbooks", "routes/cookbooks.tsx"),
  route("cookbooks/jobs/:jobId.pdf", "routes/cookbook-pdf.tsx"),
  route("exports", "routes/exports-index.tsx"),
  route("exports/selection.json", "routes/exports-selection.tsx"),
  route("exports/recipes/:recipeId.json", "routes/exports-recipe.tsx"),
  route("taxonomy", "routes/taxonomy.tsx"),
  route("public/collections/:collectionId", "routes/public-collection.tsx"),
  route("public/recipes/:recipeId", "routes/public-recipe.tsx"),
  route("recipes/new", "routes/recipe-new.tsx"),
  route("recipes/trash", "routes/recipe-trash.tsx"),
  route("recipes/:recipeId", "routes/recipe-detail.tsx"),
  route("recipes/:recipeId/media", "routes/recipe-media.tsx"),
  route("recipes/:recipeId/classification", "routes/recipe-classification.tsx"),
  route("recipes/:recipeId/edit", "routes/recipe-editor.tsx"),
] satisfies RouteConfig;
